service: site

frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  s3Bucket: ${env:FAS_SITE_S3BUCKET}
  apiEndpointHost: ${env:FAS_API_ENDPOINT_HOST}
  servicesStage: api

provider:
  name: aws
  region: eu-west-1

resources:
  Resources:
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Bucket}
        AccessControl: PublicRead

    WebAppS3BucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        Bucket:
          Ref: WebAppS3Bucket
        PolicyDocument:
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: 'Allow'
              Principal:
                CanonicalUser: !GetAtt CfOriginAccessIdentity.S3CanonicalUserId
              Resource: arn:aws:s3:::${self:custom.s3Bucket}/*

    CfOriginAccessIdentity:
      Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: 'Access S3 bucket content only through CloudFront'

    WebAppCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: 'true'
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          Origins:
          - Id: WebApp
            DomainName: ${self:custom.s3Bucket}.s3.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity:
                !Join
                  - ''
                  - - 'origin-access-identity/cloudfront/'
                    - Ref: CfOriginAccessIdentity
          - Id: WebApi
            DomainName: ${self:custom.apiEndpointHost}
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: 'true'
              Cookies:
                Forward: none
            TargetOriginId: WebApp
            ViewerProtocolPolicy: redirect-to-https
          CacheBehaviors:
            - AllowedMethods:
                - DELETE
                - GET
                - HEAD
                - OPTIONS
                - PATCH
                - POST
                - PUT
              TargetOriginId: WebApi
              PathPattern: /${self:custom.servicesStage}/*
              DefaultTTL: 0
              MinTTL: 0
              MaxTTL: 0
              ForwardedValues:
                QueryString: 'true'
                Headers:
                - Accept
                - Referer
                - Authorization
                - Content-Type
              ViewerProtocolPolicy: https-only
